### ISSUE TITLE
Cryptic error message when  undefined variable used in "active" tag of dos

### ISSUE THREAD

**Issue by mathaefele** [FZJ-JSC/jube-configs#4]
Hi Sebastian,

Everything in the title ;)
[config_bug1.txt](https://github.com/FZJ-JSC/jube-configs/files/383828/config_bug1.txt)
[config_bug2.txt](https://github.com/FZJ-JSC/jube-configs/files/383829/config_bug2.txt)
[config_works.txt](https://github.com/FZJ-JSC/jube-configs/files/383830/config_works.txt)

Cheers
Mat

**Comment by sluehrs** [comment]
Hi Mat,

thanks for the report.

Everything within the active="" is pushed to a bool(eval(...)) expression in Python. That was the reason for the cryptic error message if a pattern wasn't replaced. I added a more meaningful message to point the user into the right direction. Will be in the next release (by the end of this week)

Cheers
Sebastian
